import { useState, useEffect } from 'react'
import { getInsights } from '../../utils/api'

export default function InsightsPage() {
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    getInsights().then(d => { setData(d); setLoading(false) })
      .catch(() => setLoading(false))
  }, [])

  if (loading) return (
    <div style={{ textAlign: 'center', padding: 60, color: 'var(--text-muted)' }}>
      <div style={{ fontSize: 40, marginBottom: 12 }}>🔮</div>
      <p>Analyzing your patterns...</p>
    </div>
  )

  const insights = data?.insights?.insights || []
  const summary = data?.insights?.summary || {}
  const isString = typeof data?.insights === 'string'

  return (
    <div>
      <div style={{ marginBottom: 28 }}>
        <h2 style={{ fontSize: 28, marginBottom: 4 }}>
          AI <span className="serif-italic">Insights</span>
        </h2>
        <p style={{ color: 'var(--text-muted)', fontSize: 14 }}>
          Patterns detected from your journal entries using ML analysis
        </p>
      </div>

      <div className="card" style={{ marginBottom: 24, background: 'var(--lavender-pale)', border: '1px solid var(--lavender-light)' }}>
        <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
          <span style={{ fontSize: 24 }}>🤖</span>
          <div>
            <p style={{ fontWeight: 600, marginBottom: 4, color: 'var(--lavender)' }}>How this works</p>
            <p style={{ fontSize: 13, color: 'var(--text-muted)', lineHeight: 1.6 }}>
              MindMate uses <strong>VADER sentiment analysis</strong> (an NLP model trained on emotional text)
              to analyze your entries. It then applies pattern detection algorithms to find correlations
              between your words, days, and mood scores — giving you data-driven insights about your emotional health.
            </p>
          </div>
        </div>
      </div>

      {isString ? (
        <div className="card" style={{ textAlign: 'center', padding: 40 }}>
          <div style={{ fontSize: 48, marginBottom: 12 }}>🌱</div>
          <p style={{ color: 'var(--text-muted)', fontSize: 15 }}>{data.insights}</p>
        </div>
      ) : (
        <>
          {summary.total_entries && (
            <div style={{ display: 'flex', gap: 12, marginBottom: 24 }}>
              {[
                { label: 'Entries analyzed', value: summary.total_entries, icon: '📝' },
                { label: 'Average mood', value: `${summary.average_mood}/10`, icon: '💚' },
                { label: 'Insights found', value: summary.insight_count, icon: '✨' },
              ].map((s, i) => (
                <div key={i} className="card" style={{ flex: 1, textAlign: 'center', padding: 16 }}>
                  <div style={{ fontSize: 24, marginBottom: 4 }}>{s.icon}</div>
                  <div style={{ fontSize: 20, fontWeight: 700, fontFamily: 'DM Serif Display, serif', color: 'var(--text)' }}>{s.value}</div>
                  <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>{s.label}</div>
                </div>
              ))}
            </div>
          )}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
            {insights.map((insight, i) => (
              <div key={i} className="card" style={{
                borderLeft: `3px solid ${
                  insight.type === 'trend' ? 'var(--sage)' :
                  insight.type === 'keywords' ? 'var(--lavender)' :
                  insight.type === 'volatility' ? 'var(--warm)' : 'var(--border)'
                }`
              }}>
                <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                  <span style={{ fontSize: 28, flexShrink: 0 }}>{insight.icon}</span>
                  <div>
                    <h3 style={{ fontSize: 16, fontFamily: 'DM Sans, sans-serif', fontWeight: 600, marginBottom: 6 }}>{insight.title}</h3>
                    <p style={{ fontSize: 14, color: 'var(--text-muted)', lineHeight: 1.65 }}>{insight.detail}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </>
      )}

      <div style={{ marginTop: 24, padding: 16, background: 'var(--warm-pale)', borderRadius: 12, border: '1px solid #F0D4B8' }}>
        <p style={{ fontSize: 12, color: 'var(--text-muted)', lineHeight: 1.6 }}>
          ⚠️ <strong>Disclaimer:</strong> These insights are generated by ML algorithms and are meant for
          self-reflection only. They are not medical advice. Please consult a licensed mental health
          professional for clinical assessment or treatment.
        </p>
      </div>
    </div>
  )
}